export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
//account actions
export const GET_ACCOUNT = "GET_ACCOUNT";
export const ACCOUNT_LOADING = "ACCOUNT_LOADING";
export const ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const MOUNT_ACCOUNTS = "MOUNT_ACCOUNTS";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
